// netlify/functions/verify-pac.ts
//
// One-click PAC endorsement verification. Triggered when Ben clicks the
// "✓ Verify [School]" button in the admin notification email. The button
// is a simple GET to /api/verify-pac?t=<token> — the token is a 32-byte
// CSPRNG generated by submit.ts at INSERT time and embedded only in the
// admin email (no other surface). Single-use: token is NULLed after
// consumption.
//
// Flow:
//   1. Parse `t` query param. Validate shape (43 chars base64url for 32 bytes).
//   2. Look up the row by verify_token.
//   3. If found AND status='pending': UPDATE status='verified',
//      verified_at=NOW(), verify_token=NULL. Redirect to /pac-verified/.
//   4. If found but already verified: redirect to /pac-verified/?already=1.
//   5. If token unknown / consumed / malformed: redirect to /pac-verified/?error=invalid.
//
// Security model:
//   - Token is 32 bytes (256 bits) — not bruteforceable.
//   - Only delivered to ben@fundburnabykids.ca via the admin notification
//     email, which is forwarded by ImprovMX to Ben's personal Gmail.
//   - Single-use: token is NULLed on first successful verify, so re-clicks
//     can't re-verify or modify.
//   - DB UNIQUE INDEX on verify_token WHERE NOT NULL backstops accidental
//     duplicate INSERTs.

import type { Handler } from '@netlify/functions';
import { getSupabase, getSiteUrl } from './_shared.js';

export const handler: Handler = async (event) => {
  const token = (event.queryStringParameters?.t || '').trim();

  // Token shape check before hitting the DB. base64url of 32 bytes = 43
  // chars (no padding). Allow a small range for safety.
  if (!/^[A-Za-z0-9_-]{16,128}$/.test(token)) {
    return redirect(`${getSiteUrl()}/pac-verified/?error=invalid`);
  }

  try {
    const supabase = getSupabase();

    const { data: rows, error: selectError } = await supabase
      .from('pac_endorsements')
      .select('id, school, status')
      .eq('verify_token', token)
      .limit(1);

    if (selectError) {
      console.error('verify-pac select error:', selectError);
      return redirect(`${getSiteUrl()}/pac-verified/?error=server`);
    }

    if (!rows || rows.length === 0) {
      // Token unknown OR already consumed (set to NULL on prior verify).
      // We can't distinguish without an audit log; treat as "already
      // handled" so a stale email click reads as benign rather than an
      // error.
      return redirect(`${getSiteUrl()}/pac-verified/?already=1`);
    }

    const row = rows[0];

    if (row.status === 'verified') {
      // Defensive — shouldn't happen because token would already be NULL,
      // but if a manual UPDATE flipped status without clearing token, the
      // re-click should still feel benign.
      return redirect(`${getSiteUrl()}/pac-verified/?already=1&school=${encodeURIComponent(row.school)}`);
    }

    const { error: updateError } = await supabase
      .from('pac_endorsements')
      .update({
        status: 'verified',
        verified_at: new Date().toISOString(),
        verify_token: null,
      })
      .eq('id', row.id);

    if (updateError) {
      console.error('verify-pac update error:', updateError);
      return redirect(`${getSiteUrl()}/pac-verified/?error=server`);
    }

    return redirect(`${getSiteUrl()}/pac-verified/?ok=1&school=${encodeURIComponent(row.school)}`);
  } catch (err) {
    console.error('verify-pac unhandled error:', err);
    return redirect(`${getSiteUrl()}/pac-verified/?error=server`);
  }
};

function redirect(url: string): { statusCode: number; headers: Record<string, string>; body: string } {
  return {
    statusCode: 302,
    headers: { Location: url, 'Cache-Control': 'no-store' },
    body: '',
  };
}
